@echo off
start "" /MAX "C:\Users\Public\Desktop\VMQuickConfig"
python -c "import pyautogui as pag; pag.click(143, 487, duration=5)"
python -c "import pyautogui as pag; pag.click(155, 554, duration=2)"
python -c "import pyautogui as pag; pag.click(637, 417, duration=2)"
python -c "import pyautogui as pag; pag.click(588, 10, duration=2)"
echo ..........................................................
echo .....Brought By EXEXFMR................................
echo ......... Telegram Channel - https://t.me/program_masa ....
echo ..........................................................
echo ..Youtube Channel - https://www.youtube.com/@MASA.PRO.OFFICIAL ..
echo ..........................................................
echo User name : runneradmin
echo User Pass : EXEXFMR